CREATE TABLE orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id INTEGER NOT NULL,
    customer_name VARCHAR(50) NOT NULL,
    deadline DATE NOT NULL,
    quantity INTEGER NOT NULL,
    publisher_name VARCHAR(50) NOT NULL,

    CONSTRAINT fk_orders_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON DELETE RESTRICT
);