ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.example.MainKt.module

admin:
  email: "$ADMIN_EMAIL"
  password: "$ADMIN_PASSWORD"

database:
  url: "$DB_URL"
  driver : "org.postgresql.Driver"
  user: "$DB_USER"
  password: "$DB_PASSWORD"

jwt:
  secret: "$JWT_SECRET"
  issuer: "$JWT_ISSUER"
  audience: "$JWT_AUDIENCE"
  realm: "$JWT_REALM"
  expiration: "$JWT_EXPIRATION"